[0m17:18:44.340876 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B2003650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B2E87920>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B0FB9340>]}


============================== 17:18:44.343885 | 6022c1cb-d3ac-4428-b3d3-5002e9275ac1 ==============================
[0m17:18:44.343885 [info ] [MainThread]: Running with dbt=1.9.0
[0m17:18:44.344875 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:19:05.261989 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m17:19:05.290793 [info ] [MainThread]: 
Your new dbt project "data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:19:05.291796 [info ] [MainThread]: Setting up your profile.
[0m17:19:34.513727 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m17:19:34.514727 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m17:19:34.514727 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m22:01:51.111714 [error] [MainThread]: Encountered an error:

[0m22:01:51.177992 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 346, in run
    self.setup_profile(profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\task\init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m22:01:51.191166 [debug] [MainThread]: Command `dbt init` failed at 22:01:51.187507 after 16986.96 seconds
[0m22:01:51.199686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296B2EC3680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296C5B6A930>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000296C5947CB0>]}
[0m22:01:51.203600 [debug] [MainThread]: Flushing usage events
[0m22:01:51.747612 [debug] [MainThread]: An error was encountered while trying to flush usage events
