[0m08:26:08.827418 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8AF400950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8AD13F8C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8AC231880>]}


============================== 08:26:08.831418 | 9fb97ddc-16d5-4724-9b39-7b9b38fecc5e ==============================
[0m08:26:08.831418 [info ] [MainThread]: Running with dbt=1.8.8
[0m08:26:08.832405 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m08:26:14.730988 [debug] [MainThread]: Starter project path: C:\Users\Haroon\AppData\Local\Programs\Python\Python312\Lib\site-packages\dbt\include\starter_project
[0m08:26:14.753177 [info ] [MainThread]: 
Your new dbt project "datapipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m08:26:14.753981 [info ] [MainThread]: Setting up your profile.
[0m08:26:25.435754 [debug] [MainThread]: Spark adapter: Setting pyhive.hive logging to ERROR
[0m08:26:25.435754 [debug] [MainThread]: Spark adapter: Setting thrift.transport logging to ERROR
[0m08:26:25.436791 [debug] [MainThread]: Spark adapter: Setting thrift.protocol logging to ERROR
[0m08:28:53.043416 [info ] [MainThread]: Profile datapipeline written to C:\Users\Haroon\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m08:28:53.044795 [debug] [MainThread]: Command `dbt init` succeeded at 08:28:53.044795 after 164.31 seconds
[0m08:28:53.045794 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8AF2E30B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8AFE45100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E8C2685AF0>]}
[0m08:28:53.045794 [debug] [MainThread]: Flushing usage events
[0m16:18:59.217174 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E38D9B7230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E38D001190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E38D001850>]}


============================== 16:18:59.222179 | d6475be5-0053-4d82-996e-e52f1b22021a ==============================
[0m16:18:59.222179 [info ] [MainThread]: Running with dbt=1.8.8
[0m16:18:59.223178 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:18:59.223178 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:18:59.224179 [debug] [MainThread]: Command `dbt run` failed at 16:18:59.224179 after 0.13 seconds
[0m16:18:59.225180 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3906FB530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E38D9B7230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E3901D2B40>]}
[0m16:18:59.225180 [debug] [MainThread]: Flushing usage events
[0m16:20:27.537627 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000223F5144260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000223F75860F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000223F7AC3500>]}


============================== 16:20:27.541640 | dc014181-43c1-48d8-83b8-689420a7f1fa ==============================
[0m16:20:27.541640 [info ] [MainThread]: Running with dbt=1.8.8
[0m16:20:27.541640 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:20:27.542643 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:20:27.543632 [debug] [MainThread]: Command `dbt run` failed at 16:20:27.543632 after 0.09 seconds
[0m16:20:27.543632 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000223F5144260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000223F7528E60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000223F7BD7CE0>]}
[0m16:20:27.543632 [debug] [MainThread]: Flushing usage events
[0m16:20:56.114718 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E52C7401D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E52C005160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E52C6536E0>]}


============================== 16:20:56.119035 | 85c45525-f1a9-47cc-a8bf-a2953b6d7e8f ==============================
[0m16:20:56.119035 [info ] [MainThread]: Running with dbt=1.8.8
[0m16:20:56.119035 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:20:56.120046 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:20:56.121034 [debug] [MainThread]: Command `dbt run` failed at 16:20:56.121034 after 0.09 seconds
[0m16:20:56.122035 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E52C684CE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E52C005160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E52BFD3500>]}
[0m16:20:56.122035 [debug] [MainThread]: Flushing usage events
[0m16:33:34.115539 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ADDB01C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ADDB020C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ADDB02DB0>]}


============================== 16:33:34.119543 | 8e7a21cf-35a0-4159-9e7d-4cf7d040c0dc ==============================
[0m16:33:34.119543 [info ] [MainThread]: Running with dbt=1.8.8
[0m16:33:34.119543 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Haroon\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m16:33:34.120543 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Haroon\Documents\GitHub\end_to_end_databricks_apache_airflow_dbt_project\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:33:34.121552 [debug] [MainThread]: Command `dbt run` failed at 16:33:34.121552 after 0.09 seconds
[0m16:33:34.121552 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ADE243380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ADDB01C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024ADDB00B30>]}
[0m16:33:34.121552 [debug] [MainThread]: Flushing usage events
